[build-system]
build-backend = "cmeel"
requires = [
  "cmeel-omniorb[build] ~= 4.3.4",
  "cmeel[build]"
]

[project]
dependencies = [
  "cmeel-omniorb ~= 4.3.4"
]
description = "cmeel distribution for omniORB"
license = "LGPL-2.0-or-later"
name = "cmeel-omniorbpy"
requires-python = ">= 3.10"
version = "4.3.4"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-omniorbpy"
repository = "https://github.com/cmake-wheel/cmeel-omniorbpy.git"
upstream = "https://omniorb.sourceforge.io/"

[tool.cmeel]
run-tests = false

[tool.tomlsort]
all = true
